# Hugo 属性设置

# 网站地址
baseurl = "https://localhost:1313/"

# 网站语言
languageCode = "zh-cn"

# 网站title
title = "我的博客"

# 主题的名字，这个要跟myblog/themes 目录中的子目录的目录名一致
theme = "next"
debug = true
enableemoji = true

[params.utteranc]
  enable = true
  repo = "yexm/yexm-hugo-blog" ##换成自己得
  issueTerm = "pathname"
  theme = "github-light"

##[params.valine]
#    enable = true
#    appId = 'HB9AgpI6CEgBwBh0adQakU81-gzGzoHsz'
#    appKey = 'Luv4YGgLi4llxH16JGxabhOV'
#    verify = false # Verification code
#    avatar = 'robohash'
#    placeholder = '说点什么吧...'
#    visitor = true
#    pageSize = 10
#    highlight = true
#    recordIP = true
